// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzgiMStIeck1w92Y4-4UjqFTLquA3KPIQ',
    appId: '1:189863224347:web:822b5fae0638080b5b04be',
    messagingSenderId: '189863224347',
    projectId: 'amongus-9d388',
    authDomain: 'amongus-9d388.firebaseapp.com',
    databaseURL: 'https://amongus-9d388-default-rtdb.firebaseio.com',
    storageBucket: 'amongus-9d388.firebasestorage.app',
    measurementId: 'G-3SGH5LTYY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRWHDjWiYwoE-KLjlyEWBUgR06ViXJ3qk',
    appId: '1:189863224347:android:c9d58b98de8b05d45b04be',
    messagingSenderId: '189863224347',
    projectId: 'amongus-9d388',
    databaseURL: 'https://amongus-9d388-default-rtdb.firebaseio.com',
    storageBucket: 'amongus-9d388.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYYGFvtnpzrI5RDrIgeU_99iKrFXbTpjk',
    appId: '1:189863224347:ios:de5e4c48e91c413c5b04be',
    messagingSenderId: '189863224347',
    projectId: 'amongus-9d388',
    databaseURL: 'https://amongus-9d388-default-rtdb.firebaseio.com',
    storageBucket: 'amongus-9d388.firebasestorage.app',
    iosBundleId: 'com.example.amongus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYYGFvtnpzrI5RDrIgeU_99iKrFXbTpjk',
    appId: '1:189863224347:ios:de5e4c48e91c413c5b04be',
    messagingSenderId: '189863224347',
    projectId: 'amongus-9d388',
    databaseURL: 'https://amongus-9d388-default-rtdb.firebaseio.com',
    storageBucket: 'amongus-9d388.firebasestorage.app',
    iosBundleId: 'com.example.amongus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzgiMStIeck1w92Y4-4UjqFTLquA3KPIQ',
    appId: '1:189863224347:web:822b5fae0638080b5b04be',
    messagingSenderId: '189863224347',
    projectId: 'amongus-9d388',
    authDomain: 'amongus-9d388.firebaseapp.com',
    databaseURL: 'https://amongus-9d388-default-rtdb.firebaseio.com',
    storageBucket: 'amongus-9d388.firebasestorage.app',
    measurementId: 'G-3SGH5LTYY1',
  );

}