// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmfj7CDuZwKKguzzybBG4L8pheJENGt-g',
    appId: '1:1009487601323:web:43301c80f946ce3fe4e1ee',
    messagingSenderId: '1009487601323',
    projectId: 'amongusgdsc',
    authDomain: 'amongusgdsc.firebaseapp.com',
    databaseURL: 'https://amongusgdsc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'amongusgdsc.firebasestorage.app',
    measurementId: 'G-4WK2DQX6ZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEltUwA4_OujoKlajRjt30v8ZUnxpsmKA',
    appId: '1:1009487601323:android:df91b8baeb1a0e02e4e1ee',
    messagingSenderId: '1009487601323',
    projectId: 'amongusgdsc',
    databaseURL: 'https://amongusgdsc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'amongusgdsc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCDDmOrL01zZCBUehQH1ABy62lAAjym-g',
    appId: '1:1009487601323:ios:585c56aa2afc6e61e4e1ee',
    messagingSenderId: '1009487601323',
    projectId: 'amongusgdsc',
    databaseURL: 'https://amongusgdsc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'amongusgdsc.firebasestorage.app',
    iosBundleId: 'com.example.amongus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCDDmOrL01zZCBUehQH1ABy62lAAjym-g',
    appId: '1:1009487601323:ios:585c56aa2afc6e61e4e1ee',
    messagingSenderId: '1009487601323',
    projectId: 'amongusgdsc',
    databaseURL: 'https://amongusgdsc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'amongusgdsc.firebasestorage.app',
    iosBundleId: 'com.example.amongus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmfj7CDuZwKKguzzybBG4L8pheJENGt-g',
    appId: '1:1009487601323:web:d3c19ae9465d317ee4e1ee',
    messagingSenderId: '1009487601323',
    projectId: 'amongusgdsc',
    authDomain: 'amongusgdsc.firebaseapp.com',
    databaseURL: 'https://amongusgdsc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'amongusgdsc.firebasestorage.app',
    measurementId: 'G-B2G0ZNYGJM',
  );

}